name: Java CI with Maven and Deploy to AlwaysData

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean compile package -Pdev
        env:
          SPRING_PROFILES_ACTIVE: dev
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}


      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: GatePass
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: GatePass

      - name: Deploy to AlwaysData
        run: |
          scp my-artifact.jar myuser@ssh-alwaydata.com:/home/myuser/my-app.jar
          ssh myuser@ssh-alwaydata.com "java -jar /home/myuser/my-app.jar"
        env:
          AD_USER: ${{ secrets.ALWAYDATA_USERNAME }}
          AD_PASS: ${{ secrets.ALWAYDATA_PASSWORD }}
